"""Shared Protocol definitions for game managers.

Canonical Protocols for dependency injection across BulletManager,
BossManager, MilestoneManager, UIManager, GameLoopManager, etc.
Each file should import from here instead of defining its own copy.

Phase 2 also adds cross-layer contracts used by the UI and the
entities (input source, buff factory, game-constants view). See the
"Cross-layer contracts" section near the bottom.
"""

from collections.abc import Callable
from typing import Any, Protocol, runtime_checkable


class PlayerProtocol(Protocol):
    """Player interface used across all managers."""

    def update(self) -> None: ...
    def auto_fire(self) -> None: ...
    def cleanup_inactive_bullets(self) -> None: ...
    def get_bullets(self) -> list[Any]: ...
    def remove_bullet(self, bullet: Any) -> None: ...
    def get_weapon_status(self) -> dict[str, Any]: ...
    def get_boost_status(self) -> dict[str, Any]: ...

    bullet_damage: float
    fire_interval: int
    is_controls_locked: bool
    health: int
    max_health: int

    @property
    def active(self) -> bool: ...


class GameControllerProtocol(Protocol):
    """Game controller interface used across managers."""

    @property
    def state(self) -> Any: ...
    def is_playing(self) -> bool: ...
    def update(self, player: Any, has_regen: bool) -> None: ...
    def on_enemy_killed(self, score: int) -> None: ...
    def on_boss_killed(self, score: int) -> None: ...
    def show_notification(self, message: str) -> None: ...
    def get_next_threshold(self) -> float: ...
    def get_next_progress(self) -> int: ...
    @property
    def difficulty_manager(self) -> Any: ...


class GameRendererProtocol(Protocol):
    """Game renderer interface used by GameLoopManager and UIManager."""

    def render(self, surface: Any, state: Any, entities: Any) -> None: ...
    def update_death_animation(self) -> None: ...


class SpawnControllerProtocol(Protocol):
    """Spawn controller interface used by GameLoopManager and BulletManager."""

    def update(self, score: int, slow_factor: float, player_pos: tuple[float, float] | None = None) -> bool: ...
    def balance_for_player_dps(self, player_dps: float) -> None: ...
    def spawn_boss(self, cycle_count: int, bullet_damage: float, player_dps: float | None = None) -> Any: ...
    def cleanup(self) -> None: ...
    @property
    def enemies(self) -> list[Any]: ...
    @property
    def boss(self) -> Any: ...
    @property
    def enemy_bullets(self) -> list[Any]: ...


class RewardSystemProtocol(Protocol):
    """Reward system interface used across managers."""

    @property
    def slow_factor(self) -> float: ...
    @property
    def unlocked_buffs(self) -> list[str]: ...
    @property
    def explosive_level(self) -> int: ...
    @property
    def piercing_level(self) -> int: ...
    def apply_lifesteal(self, player: Any, score: int) -> None: ...


class BulletManagerProtocol(Protocol):
    """Bullet manager interface used by GameLoopManager."""

    def update_all(self) -> None: ...
    def cleanup(self) -> None: ...
    def clear_enemy_bullets(self, include_clear_immune: bool = False) -> None: ...


class BossManagerProtocol(Protocol):
    """Boss manager interface used by GameLoopManager."""

    def update(self, player: Any) -> None: ...
    def on_boss_hit(self, score: int) -> None: ...
    def on_boss_killed(self) -> None: ...
    @property
    def boss(self) -> Any: ...


class CollisionControllerProtocol(Protocol):
    """Collision controller interface used by GameLoopManager."""

    def check_all_collisions(self, **kwargs: Any) -> None: ...
    def set_explosion_callback(self, callback: Any) -> None: ...


class RewardSelectorProtocol(Protocol):
    """Protocol for reward selector input methods."""

    def handle_input(self, event: Any) -> None: ...
    @property
    def visible(self) -> bool: ...


class GiveUpDetectorProtocol(Protocol):
    """Protocol for give-up detector methods."""

    def update(self, delta: float) -> None: ...
    def is_active(self) -> bool: ...
    def get_progress(self) -> float: ...


class GiveUpUIProtocol(Protocol):
    """Protocol for give-up UI methods."""

    def show(self) -> None: ...
    def hide(self) -> None: ...
    def update_progress(self, progress: float) -> None: ...
    def render(self, surface: Any) -> None: ...


# ---------------------------------------------------------------------------
# Cross-layer contracts (Phase 2)
#
# These break the entity/config/ui -> game.systems / game.constants
# dependency cycle by giving the lower layers a structural contract to
# depend on instead of a concrete import.
# ---------------------------------------------------------------------------


@runtime_checkable
class InputSourceProtocol(Protocol):
    """Duck-typed input source for the player.

    The :class:`airwar.entities.player.Player` only needs to read input
    state; it should not need to know whether the source is the live
    Pygame handler, a recording, or a unit-test stub. The real
    :class:`airwar.input.input_handler.PygameInputHandler` already
    matches this protocol structurally.
    """

    def get_movement_direction(self) -> Any: ...
    def is_pause_pressed(self) -> bool: ...
    def is_boost_pressed(self) -> bool: ...
    def is_boost_just_pressed(self) -> bool: ...
    def is_precision_pressed(self) -> bool: ...
    def is_precision_just_pressed(self) -> bool: ...


@runtime_checkable
class BuffFactoryProtocol(Protocol):
    """Single-method protocol — the UI only needs ``create_buff(name)``."""

    def __call__(self, name: str) -> object: ...


# Convenience callable alias for the common case.
BuffFactory = Callable[[str], object]


@runtime_checkable
class RequisitionConstantsProtocol(Protocol):
    """Subset of ``GAME_CONSTANTS.REQUISITION`` accessed by the UI."""

    REPAIR_COST: int
    RECHARGE_COST: int


@runtime_checkable
class GameConstantsProtocol(Protocol):
    """Subset of ``GAME_CONSTANTS`` accessed by the UI."""

    REQUISITION: RequisitionConstantsProtocol


@runtime_checkable
class DifficultyManagerProtocol(Protocol):
    """Subset of ``DifficultyManager`` accessed by the UI panel."""

    def get_current_difficulty(self) -> object: ...


# ---------------------------------------------------------------------------
# F06 I3 / Phase 5-α (revoked 2026-06-10, P0-5):
#
#   The 8-way GameSceneProtocol split (IScoreProvider / ICycleProvider /
#   IPauseProvider / IBuffProvider / IDifficultyProvider /
#   IPlayerAccessProvider / INotificationProvider / IHomecomingProvider /
#   IGameLifecycleProvider) was introduced as a speculative "focused
#   contract" decomposition. A 2026-06-10 audit confirmed:
#
#     - 0 runtime consumers (no production code imported any sub-protocol)
#     - 0 test consumers (no test imported any sub-protocol)
#     - 4 accompanying ``# type: ignore`` lines existed solely to make
#       ``hasattr()`` materialize attributes on the empty Protocol bodies
#
#   The split never landed a real consumer, and the union of 9
#   sub-protocols plus 4 class-level descriptor injections made
#   GameSceneProtocol harder to read for no measurable win. Reverted
#   to a single flat Protocol below.
#
#   The 9 sub-protocol definitions are preserved here as a comment for
#   future re-spawn: if a real consumer (e.g. a focused test fake that
#   only needs the score surface) emerges, uncomment the relevant
#   sub-protocol block and re-add it to the GameSceneProtocol bases.
#
#   --- IScoreProvider (revoked) ---
#   @runtime_checkable
#   class IScoreProvider(Protocol):
#       def set_score(self, value: int) -> None: ...
#       def add_score(self, amount: int) -> None: ...
#       def add_kill(self) -> None: ...
#       def add_boss_kill(self) -> None: ...
#       def get_kill_count(self) -> int: ...
#       def get_boss_kill_count(self) -> int: ...
#
#   --- ICycleProvider (revoked) ---
#   @runtime_checkable
#   class ICycleProvider(Protocol):
#       def set_cycle_count(self, value: int) -> None: ...
#       def restore_from_save(self, save_data: Any) -> None: ...
#       def create_save_data(self) -> Any: ...
#       def is_game_over(self) -> bool: ...
#
#   --- IPauseProvider (revoked) ---
#   @runtime_checkable
#   class IPauseProvider(Protocol):
#       def pause(self) -> None: ...
#       def resume(self) -> None: ...
#       def paused(self) -> bool: ...
#       def consume_pause_request(self) -> bool: ...
#
#   --- IBuffProvider (revoked) ---
#   @runtime_checkable
#   class IBuffProvider(Protocol):
#       def unlocked_buffs(self) -> list[str]: ...
#
#   --- IDifficultyProvider (revoked) ---
#   @runtime_checkable
#   class IDifficultyProvider(Protocol):
#       def set_difficulty(self, value: str) -> None: ...
#       def difficulty(self) -> str: ...
#
#   --- IPlayerAccessProvider (revoked) ---
#   @runtime_checkable
#   class IPlayerAccessProvider(Protocol):
#       def player(self) -> object: ...
#       def get_boss(self) -> Any: ...
#       def get_enemies(self) -> list[Any]: ...
#       def clear_boss(self) -> None: ...
#
#   --- INotificationProvider (revoked) ---
#   @runtime_checkable
#   class INotificationProvider(Protocol):
#       def show_notification(self, message: str) -> None: ...
#
#   --- IHomecomingProvider (revoked) ---
#   @runtime_checkable
#   class IHomecomingProvider(Protocol):
#       def is_homecoming_active(self) -> bool: ...
#       def is_homecoming_locked(self) -> bool: ...
#       def is_homecoming_complete(self) -> bool: ...
#       def event_bus(self) -> object: ...
#       def is_mothership_docked(self) -> bool: ...
#
#   --- IGameLifecycleProvider (revoked) ---
#   @runtime_checkable
#   class IGameLifecycleProvider(Protocol):
#       def update(self, *args: Any, **kwargs: Any) -> None: ...
#       def render(self, surface: Any) -> None: ...
#       def handle_events(self, event: Any) -> None: ...
#       def enter(self, **kwargs: Any) -> None: ...
#       def exit(self) -> None: ...
# ---------------------------------------------------------------------------


@runtime_checkable
class GameSceneProtocol(Protocol):
    """Full structural protocol for the public surface of GameScene.

    The historical decomposition into 8 focused sub-protocols was
    revoked in P0-5 (2026-06-10) after audit confirmed zero runtime
    + zero test consumers. Sub-protocols are preserved as comments
    above for future re-spawn when a real consumer emerges.
    """

    # --- Score / kill-count surface ---
    def set_score(self, value: int) -> None: ...
    def add_score(self, amount: int) -> None: ...
    def add_kill(self) -> None: ...
    def add_boss_kill(self) -> None: ...
    def get_kill_count(self) -> int: ...
    def get_boss_kill_count(self) -> int: ...

    # --- Cycle counter and save/load surface ---
    def set_cycle_count(self, value: int) -> None: ...
    def restore_from_save(self, save_data: Any) -> None: ...
    def create_save_data(self) -> Any: ...
    def is_game_over(self) -> bool: ...

    # --- Pause / resume surface ---
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def paused(self) -> bool: ...
    def consume_pause_request(self) -> bool: ...

    # --- Unlocked-buff surface ---
    def unlocked_buffs(self) -> list[str]: ...

    # --- Difficulty get/set surface ---
    def set_difficulty(self, value: str) -> None: ...
    def difficulty(self) -> str: ...

    # --- Player / boss / enemy accessor surface ---
    def player(self) -> object: ...
    def get_boss(self) -> Any: ...
    def get_enemies(self) -> list[Any]: ...
    def clear_boss(self) -> None: ...

    # --- Notification surface ---
    def show_notification(self, message: str) -> None: ...

    # --- Homecoming / mothership query surface ---
    def is_homecoming_active(self) -> bool: ...
    def is_homecoming_locked(self) -> bool: ...
    def is_homecoming_complete(self) -> bool: ...
    def event_bus(self) -> object: ...
    def is_mothership_docked(self) -> bool: ...

    # --- Scene-lifecycle surface ---
    def update(self, *args: Any, **kwargs: Any) -> None: ...
    def render(self, surface: Any) -> None: ...
    def handle_events(self, event: Any) -> None: ...
    def enter(self, **kwargs: Any) -> None: ...
    def exit(self) -> None: ...


# ---------------------------------------------------------------------------
# F06 I4: LockRequestProtocol — runtime_checkable contract for LockRequest
# ---------------------------------------------------------------------------


@runtime_checkable
class LockRequestProtocol(Protocol):
    """Structural contract for :class:`airwar.game.systems.lock_manager.LockRequest`.

    F06 I4: this Protocol lets the LockManager be tested with a duck-typed
    mock object (``isinstance(req, LockRequestProtocol) == True``) instead
    of having to import the concrete ``LockRequest`` dataclass.
    """

    invincible: bool
    lock_controls: bool
    is_paused: bool
    is_silent_invincible: bool
    invincibility_duration: int
