"""Shared Protocol definitions for game managers.

Canonical Protocols for dependency injection across BulletManager,
BossManager, MilestoneManager, UIManager, GameLoopManager, etc.
Each file should import from here instead of defining its own copy.
"""

from typing import Any, Protocol


class PlayerProtocol(Protocol):
    """Player interface used across all managers."""

    def update(self) -> None: ...
    def auto_fire(self) -> None: ...
    def cleanup_inactive_bullets(self) -> None: ...
    def get_bullets(self) -> list[Any]: ...
    def remove_bullet(self, bullet: Any) -> None: ...
    def get_weapon_status(self) -> dict[str, Any]: ...
    def get_boost_status(self) -> dict[str, Any]: ...

    bullet_damage: float
    fire_interval: int
    is_controls_locked: bool
    health: int
    max_health: int

    @property
    def active(self) -> bool: ...


class GameControllerProtocol(Protocol):
    """Game controller interface used across managers."""

    @property
    def state(self) -> Any: ...
    def is_playing(self) -> bool: ...
    def update(self, player: Any, has_regen: bool) -> None: ...
    def on_enemy_killed(self, score: int) -> None: ...
    def on_boss_killed(self, score: int) -> None: ...
    def show_notification(self, message: str) -> None: ...
    def get_next_threshold(self) -> float: ...
    def get_next_progress(self) -> int: ...
    @property
    def difficulty_manager(self) -> Any: ...


class GameRendererProtocol(Protocol):
    """Game renderer interface used by GameLoopManager and UIManager."""

    def render(self, surface: Any, state: Any, entities: Any) -> None: ...
    def update_death_animation(self) -> None: ...


class SpawnControllerProtocol(Protocol):
    """Spawn controller interface used by GameLoopManager and BulletManager."""

    def update(self, score: int, slow_factor: float, player_pos: tuple[float, float] | None = None) -> bool: ...
    def balance_for_player_dps(self, player_dps: float) -> None: ...
    def spawn_boss(self, cycle_count: int, bullet_damage: float, player_dps: float | None = None) -> Any: ...
    def cleanup(self) -> None: ...
    @property
    def enemies(self) -> list[Any]: ...
    @property
    def boss(self) -> Any: ...
    @property
    def enemy_bullets(self) -> list[Any]: ...


class RewardSystemProtocol(Protocol):
    """Reward system interface used across managers."""

    @property
    def slow_factor(self) -> float: ...
    @property
    def unlocked_buffs(self) -> list[str]: ...
    @property
    def explosive_level(self) -> int: ...
    @property
    def piercing_level(self) -> int: ...
    def apply_lifesteal(self, player: Any, score: int) -> None: ...


class BulletManagerProtocol(Protocol):
    """Bullet manager interface used by GameLoopManager."""

    def update_all(self) -> None: ...
    def cleanup(self) -> None: ...
    def clear_enemy_bullets(self, include_clear_immune: bool = False) -> None: ...


class BossManagerProtocol(Protocol):
    """Boss manager interface used by GameLoopManager."""

    def update(self, player: Any) -> None: ...
    def on_boss_hit(self, score: int) -> None: ...
    def on_boss_killed(self) -> None: ...
    @property
    def boss(self) -> Any: ...


class CollisionControllerProtocol(Protocol):
    """Collision controller interface used by GameLoopManager."""

    def check_all_collisions(self, **kwargs: Any) -> None: ...
    def set_explosion_callback(self, callback: Any) -> None: ...


class RewardSelectorProtocol(Protocol):
    """Protocol for reward selector input methods."""

    def handle_input(self, event: Any) -> None: ...
    @property
    def visible(self) -> bool: ...


class GiveUpDetectorProtocol(Protocol):
    """Protocol for give-up detector methods."""

    def update(self, delta: float) -> None: ...
    def is_active(self) -> bool: ...
    def get_progress(self) -> float: ...


class GiveUpUIProtocol(Protocol):
    """Protocol for give-up UI methods."""

    def show(self) -> None: ...
    def hide(self) -> None: ...
    def update_progress(self, progress: float) -> None: ...
    def render(self, surface: Any) -> None: ...
